### ISSUE TITLE
Someone has blocked my VPN

### ISSUE THREAD

**Issue by Maseratiboy** [nathanp/crypto-price-widget#104]
Great widget, but today someone blocked my VPN and no data is displayed. Where should I write to get the blockage removed?

**Comment by nathanp** [comment]
That's not something we would be able to help with. I would recommend contacting your VPN provider.

**Comment by Maseratiboy** [comment]
I disagree. 
I am a VPN server administrator with root rights. I have checked, there are no blockages on the server. The blockage is on the side of your hosting or firewall.
Tell me your contact, I'll send the IP to check.

**Comment by nathanp** [comment]
We don't have a server. It may the public API that we are using. 
The app uses the CryptoCompare API - https://min-api.cryptocompare.com/

**Comment by Maseratiboy** [comment]
I have written to cryptocompare.com tech support. They replied that I should use their API. How do I put it into the widget?

**Comment by Maseratiboy** [comment]
I have solved the problem, but it is global in nature.

Cryptocompare gave me an answer:
_We have reset the rate limits for your IP address which should allow you to get updates again, however please be aware that we will not be able to do this every time the rate limit is hit. If this happens again you will need to request that the cryptopricewidget developer reduces the number of calls the widget makes or integrates API keys to allow for higher rate limits._

Can you add a field for API key in the widget settings?
