### ISSUE TITLE
Server distributing infected version

### ISSUE THREAD

**Issue by Earlz** [nathanp/crypto-price-widget#14]
I'm receiving reports (as well as my own team's analysis) that the version of the tool being distributed on https://www.cryptopricewidget.net is infected with some kind of wallet stealing software, and potentially other things. This has already caused a loss in our community of around $30,000 worth of coin.

**Comment by nathanp** [comment]
@Earlz cryptopricewidget [dot] net is NOT the website where this app is distributed.
I am the creator of this app and the correct website is as stated in this repo - https://cryptopricewidget.com
Sounds like you got directed to a hacked/phishing clone of my site, I am very sorry.
Where did you see a link to the .net site?

**Comment by nathanp** [comment]
I found the spam links on reddit and have commented to warn future visitors and flagged the posts to reddit.

**Comment by Earlz** [comment]
Thanks, I noticed immediately after posting this that the scam URL is .NET
