### ISSUE TITLE
Offline while pc is online

### ISSUE THREAD

**Issue by UveysU** [nathanp/crypto-price-widget#25]
Yesterday the widget stopped working because it says the pc has no internet connection.
However, my computer clearly has internet access and the widget is not blocked by firewall.
Any idea how to solve this ?

**Comment by rogercadafalch** [comment]
Same to me, I'm online, everything works fine, but when I open the widget it just says ''Uh-oh! Looks like you're offline. Reconnect, then reload the app.''

I can't figure how to make it work

**Comment by nathanp** [comment]
I've had this happen when Cryptocompare's API servers get overloaded. Eventually, it should load. @UveysU and @rogercadafalch are you still having this problem?

**Comment by UveysU** [comment]
No . It loaded eventually , as you mentioned :)
