### ISSUE TITLE
Add ICX Please (ICON coin from South Korea)

### ISSUE THREAD

**Issue by yummeez** [nathanp/crypto-price-widget#31]
There are several coins listed when you search for ICON, including ICONOMI and ICONIC, but the main coin called ICON aka ICX is missing. Can you please add it to your widget? I thought ICON coin listen in there now was the ICX ICON coin and have been watching the wrong prices for over a week! Thanks in advance.

**Comment by nathanp** [comment]
ICX will be added in the upcoming v2 release.

**Comment by nathanp** [comment]
@yummeez ICX has been added in 1.4.0.
