### ISSUE TITLE
Crypto stopped refreshing, than the app broke!

### ISSUE THREAD

**Issue by singatias** [nathanp/crypto-price-widget#54]
Yesterday the crypto stopped refreshing so I restarted the app and now no crypto show up on the app.

https://gyazo.com/b763d576a968efa7dab035cdb6512b47

**Comment by Qayden** [comment]
Same happened to a family member of mine, and a few days later my own widget also shows a black screen only (different home, different IP).
Reinstall and deleting the roaming folders did not help.
