### ISSUE TITLE
Unable to change base currency to BTC

### ISSUE THREAD

**Issue by jonlorusso** [nathanp/crypto-price-widget#6]
Steps to reproduce:
1. Click gear icon (Settings)
2. Change Base currency to BTC
3. Click Save

Expected:
Base currency is switched to BTC.

Actual:
Continues to show coins in USD value.

**Comment by nathanp** [comment]
Congrats! The first user-assigned issue! 😃 
Thank you for your input, this has been addressed in the latest commit. Will be in the 1.0.1 version, which I hope to be releasing later this week.
