### ISSUE TITLE
No Values display (1.4.0)  since 21/04

### ISSUE THREAD

**Issue by mobilisinuk** [nathanp/crypto-price-widget#73]
same as last time was working fine until 2 days ago
thx for your help really like the tool

also would be nice to customise font size from the program rather than touching the code and the template?

**Comment by Hackmastr** [comment]
https://github.com/nathanp/crypto-price-widget/issues/72

**Comment by mobilisinuk** [comment]
thx for hard work working back this morning!

**Comment by Hackmastr** [comment]
> thx for hard work working back this morning!

It's just the monthly reset :P. After probably 15 days it'll stop working. Don't worry tho! By then I'll have the new api implemented.
