### ISSUE TITLE
It just opens to a blank black window

### ISSUE THREAD

**Issue by rmcc4444** [nathanp/crypto-price-widget#87]
This is very weird. Sometimes it will load fine and other times it will just be a blank black rectangle.  I've tried re-downloading and putting in a new directory. No luck.  This is on Windows 10. I'd be happy to share log files. thanks

**Comment by Oracle76** [comment]
When this happens disconnect your VPN then reconnect. Problem will be solved. Happens here every few days.

**Comment by rmcc4444** [comment]
> When this happens disconnect your VPN then reconnect. Problem will be solved. Happens here every few days.

.. thanks, I'm not connected via vpn. I actually forgot it was installed in just a couple days ago it started working again. When you say VPN, do you mean cable modem if that's what I use?

**Comment by Oracle76** [comment]
You could try disconnecting your cable modem for a minute or so then reconnecting. Not sure if your setup uses a static or dynamic IP address. When I disconnect my VPN and reconnect I get a new IP address. It appears CPW is using a service that limits the number of daily calls for prices. After a while you use up that number tied to that IP address. A new IP address lets the price updates begin again. Hope that helps.

**Comment by rmcc4444** [comment]
> You could try disconnecting your cable modem for a minute or so then reconnecting. Not sure if your setup uses a static or dynamic IP address. When I disconnect my VPN and reconnect I get a new IP address. It appears CPW is using a service that limits the number of daily calls for prices. After a while you use up that number tied to that IP address. A new IP address lets the price updates begin again. Hope that helps.

Ahhhh. Makes sense. Inside my home network I use dynamic but my external facing IP is static. Next time it happens I'll connect with the VPN and see what happens. Thank you

**Comment by rmcc4444** [comment]
Done
